# Generated by Django 4.2.2 on 2023-07-14 23:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('autor', models.EmailField(max_length=254)),
                ('destinatario', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
    ]
