# Generated by Django 4.2.2 on 2023-07-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='autor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='destinatario',
            field=models.CharField(max_length=30),
        ),
    ]
