# Generated by Django 4.2.2 on 2023-07-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_alter_mensaje_autor_alter_mensaje_destinatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='texto',
        ),
    ]
