# Generated by Django 4.2.2 on 2023-07-15 21:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_remove_mensaje_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
