# Generated by Django 4.2.2 on 2023-07-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_usuario_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
