# Generated by Django 4.2.2 on 2023-07-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_usuario_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='autor',
            field=models.EmailField(max_length=254),
        ),
    ]
