# Generated by Django 4.2.2 on 2023-07-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_alter_usuario_autor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Producto',
        ),
    ]
