# Generated by Django 4.2.2 on 2023-07-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_rename_usuario_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='edad',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='email',
        ),
        migrations.AddField(
            model_name='producto',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
