# Generated by Django 4.2.2 on 2023-07-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_rename_edad_producto_precio_remove_producto_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='avatar',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
