# Generated by Django 4.2.2 on 2023-07-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_remove_producto_avatar_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
