# Generated by Django 4.2.2 on 2023-07-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_producto_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
