# Generated by Django 4.2.2 on 2023-07-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_alter_producto_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='autor',
            new_name='email_vendedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_vendedor',
            field=models.CharField(default='yo', max_length=20),
            preserve_default=False,
        ),
    ]
