# Generated by Django 4.2.2 on 2023-07-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
