# Generated by Django 4.2.2 on 2023-07-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_infoextra_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='red_social',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
