# Generated by Django 4.2.2 on 2023-07-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_infoextra_red_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='email',
        ),
    ]
